spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mercari
    username: postgres
    password: mercari
server:
 servlet:
  context-path: /mercari